# This is a basic workflow to help you get started with Actions

name: Build document

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: "h1"
          root_file: "h1.tex"
          latexmk_use_xelatex: true
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: "h2"
          root_file: "h2.tex"
          latexmk_shell_escape: true
          latexmk_use_xelatex: true
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: "h3"
          root_file: "h3.tex"
          latexmk_shell_escape: true
          latexmk_use_xelatex: true
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: "h4"
          root_file: "h4.tex"
          latexmk_shell_escape: true
          latexmk_use_xelatex: true
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: h1
          path: |
            h1/*.pdf
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: h2
          path: |
            h2/*.pdf
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: h3
          path: |
            h3/*.pdf
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: h3
          path: |
            h3/*.pdf
